services:
  - type: web
    name: w-phex
    runtime: static
    plan: free
    buildCommand: echo "static site"
    staticPublishPath: docs
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
