services:
  - type: web
    name: w-phex
    runtime: static
    plan: free
    buildCommand: mkdir -p build && cp -R docs/. build/
    staticPublishPath: build
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
